# Default values for jobs-suite-dispatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linearb-on-prem.jfrog.io/jobs-suite-dispatcher
  pullPolicy: Always
  tag: "v2.0.2-k8s"
  env:
    parametersStore:
      - name: "EXECUTION_MODE"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "EXECUTION_MODE"
      - name: "AWS_DEFAULT_REGION"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "AWS_DEFAULT_REGION"
      - name: "CACHE_REDIS_PORT"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "CACHE_REDIS_PORT"
      - name: "CACHE_REDIS_DB"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "CACHE_REDIS_DB"
      - name: "RABBITMQ_USER"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBITMQ_USER"
      - name: "CACHE_REDIS_PORT"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "CACHE_REDIS_PORT"
      - name: "RABBITMQ_PASSWORD"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBITMQ_PASSWORD"
      - name: "RABBITMQ_PORT"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBITMQ_PORT"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
