# Default values for agent-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linearb-on-prem.jfrog.io/agent-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.0.2-k8s"
  env:
    parametersStore:
      - name: "PLATFORM"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "PLATFORM"
      - name: "ONPREM_LINTA_IMAGE"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "ONPREM_LINTA_IMAGE"
      - name: "LINB_REST_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "LINB_REST_SERVICE_URL"
      - name: "DOCKER_CLEANUP_TIME_DELTA"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "DOCKER_CLEANUP_TIME_DELTA"
      - name: "ORG_ID"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "ORG_ID"
      - name: "ONGOING_INITIAL_BACKWARD_DAYS"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "ONGOING_INITIAL_BACKWARD_DAYS"
      - name: "ONGOING_CONCURRENT_PROCESSES"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "ONGOING_CONCURRENT_PROCESSES"
      - name: "AWS_DEFAULT_REGION"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "AWS_DEFAULT_REGION"
      - name: "CACHE_REDIS_PORT"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "CACHE_REDIS_PORT"
      - name: "CACHE_REDIS_DB"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "CACHE_REDIS_DB"
      - name: "CACHE_REDIS_HOST"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "CACHE_REDIS_HOST"

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
