apiVersion: v1
data:
  .dockerconfigjson: eyAiYXV0aHMiOiB7ICJodHRwczovL2xpbmVhcmItb24tcHJlbS5qZnJvZy5pbyI6IHsgInVzZXJuYW1lIjogIm9uLXByZW0iLCAicGFzc3dvcmQiOiAiQUtDcDhvaG81S1llVkhUTUt0ekZvSkxCdms1c0pNd1d6dUpBS3FGekFoSGNGaGtIamFYdnVGWlpUenczTW91V1lyQUhlRG5vdiIgfSB9IH0=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: infra
    meta.helm.sh/release-namespace: linearb2
  creationTimestamp: "2023-06-19T10:56:42Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: regcred
  namespace: linearb2
  resourceVersion: "54704567"
  uid: 07a11afb-6158-4a4e-8f37-1383d464f087
type: kubernetes.io/dockerconfigjson