{{- define "libchart.scaledobject" -}}
{{- $build := .build }}
{{- $fullName := include "libchart.fullname" . }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ $build }}-{{ $fullName }}"
  namespace: app
spec:
  #  pollingInterval: 30                              # Optional. Default: 30 seconds
  #  cooldownPeriod: 300                              # Optional. Default: 300 seconds
  #  idleReplicaCount: 0                              # Optional. Default: ignored, must be less than minReplicaCount
  minReplicaCount: {{ .Values.kedaAutoscaling.minReplicas }}                                # Optional. Default: 0
  maxReplicaCount: {{ .Values.kedaAutoscaling.maxReplicas }}                                # Optional. Default: 100
  #  fallback: # Optional. Section to specify fallback options
  #    failureThreshold: 3                              # Mandatory if fallback section is included
  #    replicas: 6                                      # Mandatory if fallback section is included
  #  advanced: # Optional. Section to specify advanced options
  #    restoreToOriginalReplicaCount: false        # Optional. Default: false
  #    horizontalPodAutoscalerConfig: # Optional. Section to specify HPA related options
  #      behavior: # Optional. Use to modify HPA's scaling behavior
  #        scaleDown:
  #          stabilizationWindowSeconds: 300
  #          policies:
  #            - type: Percent
  #              value: 100
  #              periodSeconds: 15
  scaleTargetRef:
    name: "{{ $build }}-{{ $fullName }}"
  triggers:
    - type: {{ .Values.kedaAutoscaling.type }}
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
      metadata:
        {{- if eq .Values.kedaAutoscaling.type "prometheus"}}
        serverAddress: http://prom-stack-kube-prometheus-prometheus.infra.svc.cluster.local:9090
        metricName: "nginx_ingress_controller_requests"
        threshold: {{ .Values.kedaAutoscaling.threshold | quote}}
        query: {{ .Values.kedaAutoscaling.query }}
        {{- else }}
        queueURL: {{ .Values.kedaAutoscaling.queueURL  }}
        awsRegion: {{ .Values.kedaAutoscaling.region  }}
        queueLength: {{ .Values.kedaAutoscaling.queueLength | quote}}
        # https://github.com/kedacore/keda/issues/1408#issuecomment-954004049
        identityOwner: operator
        {{- end }}
{{- end -}}