{{- define "libchart.service" -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ include "libchart.fullname" . }}"
  labels:
    {{- include "libchart.labels" . | nindent 4 }}
    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    
    {{- if .Values.additionalPorts }}
    {{- range .Values.additionalPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .name }}
    {{- end }}
    {{- end }}

  selector:
    {{- include "libchart.selectorLabels" . | nindent 4 }}
    
{{- end }}