# Default values for scheduler-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linearb-on-prem.jfrog.io/scheduler
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  command: ["./run-celery.sh"]
  env:
    chartValuesV2:
      - name: RABBITMQ_BATCH_JOBS_QUEUE_NAME
        value: "q-batch-jobs"
    configMap:
      - name: "ON_PREM_API_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "ON_PREM_API_SERVICE_URL"
      - name: "RABBITMQ_USER"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBITMQ_USER"
      - name: "RABBITMQ_PASSWORD"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBITMQ_PASSWORD"
      - name: "RABBIT_SERVER"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBIT_SERVER"
      - name: "RABBITMQ_PORT"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "RABBITMQ_PORT"
      - name: "ONPREM_LINTA_IMAGE"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "ONPREM_LINTA_IMAGE"
      - name: "LINB_REST_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "LINB_REST_SERVICE_URL"
      - name: "PR_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "PR_SERVICE_URL"
      - name: "SETTINGS_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "SETTINGS_SERVICE_URL"
      - name: "PM_REST_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "PM_REST_SERVICE_URL"
      - name: "LINTA_REST_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "LINTA_REST_SERVICE_URL"
      - name: "LINTA_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "LINTA_SERVICE_URL"
      - name: "SENSORS_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "SENSORS_SERVICE_URL"
      - name: "AGENT_SERVICE_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "AGENT_SERVICE_URL"
      - name: "INFERENCE_ESTIMATED_REVIEW_URL"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "INFERENCE_ESTIMATED_REVIEW_URL"
      - name: "AWS_DEFAULT_REGION"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "AWS_DEFAULT_REGION"
      - name: "AWS_ACCESS_KEY_ID"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "AWS_ACCESS_KEY_ID"
      - name: "AWS_SECRET_ACCESS_KEY"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "AWS_SECRET_ACCESS_KEY"
      - name: "S3_UPLOAD_THREAD_POOL_SIZE"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "S3_UPLOAD_THREAD_POOL_SIZE"
      - name: "SCHEDULER_NUMBER_OF_CELERY_WORKERS"
        valueFrom:
          configMapKeyRef:
            name: "charts-values"
            key: "SCHEDULER_NUMBER_OF_CELERY_WORKERS"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
