{{- if eq .Values.image.env.K8S_PLATFORM "eks" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "infra.minio_pv_size" . | quote }}
{{- end }}