{{- if eq "k3d" (.Values.image.env.chartValues.K8S_PLATFORM | toString) -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    type: local
    purpose: minio
spec:
  storageClassName: manual
  capacity:
    storage: {{ include "infra.minio_pv_size" . | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/linearb/k3dvol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  selector:
    matchLabels:
      purpose: minio
{{- end }}