{{- if eq "eks" (.Values.image.env.chartValues.K8S_PLATFORM | toString) -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
{{- end }}