---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods"]
  verbs: ["create", "list", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator
subjects:
- kind: ServiceAccount
  name: agent-cli
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: scheduler-worker
  namespace: {{ .Release.Namespace }}
